# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' select_xx_xy
#'
#' @param xx_dt generate by ft[, FM::pcor(.SD), .SDcols= cols]
#' @param pcor_sorted_x, x vec sorted by pcor, could has dupe
#' @param xx_threshold, pcor threshold
#' @return list
#' @export
select_xx_xy <- function(xx_dt, pcor_sorted_x, xx_threshold = 0.8) {
    .Call(`_FQA_select_xx_xy`, xx_dt, pcor_sorted_x, xx_threshold)
}

