# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' get_binned_stats
#'
#' @param x vector, bin divided by x, not y
#' @param y vector
#' @param n_bin bin num
#' @param threads thread num
#' @export
get_binned_stats <- function(x, y, n_bin, threads = 1L) {
    .Call(`_FM_get_binned_stats`, x, y, n_bin, threads)
}

#' fast_hist_n
#'
#' @param x vector
#' @param bins bin num
#' @param min_val min val
#' @param max_val max val
#' @param threads thread num
#' @export
fast_hist_n <- function(x, bins, min_val = NA_real_, max_val = NA_real_, threads = 1L) {
    .Call(`_FM_fast_hist_n`, x, bins, min_val, max_val, threads)
}

#' fm_get_ret
#'
#' @param x vector
#' @param lag lag
#' @param skip skip
#' @export
fm_get_ret <- function(x, lag, skip = 0L) {
    .Call(`_FM_fm_get_ret`, x, lag, skip)
}

#' t0_nav
#'
#' @param signals vector
#' @param ret1 next bar's return
#' @param long_t >= threshold, open long
#' @param short_t <= threshold, open short
#' @param cost cost
#' @export
t0_nav <- function(signals, ret1, long_t, short_t, cost = 0) {
    .Call(`_FM_t0_nav`, signals, ret1, long_t, short_t, cost)
}

#' factor_nav, nav = cumsum(factor * ret1)
#'
#' @param signals vector
#' @param ret1 next bar's return
#' @export
factor_nav <- function(signals, ret1) {
    .Call(`_FM_factor_nav`, signals, ret1)
}

#' cumret
#'
#' @param ret1 next bar's return
#' @export
cumret <- function(ret1) {
    .Call(`_FM_cumret`, ret1)
}

#' sharpe, mean / sd
#'
#' @param rets vector
#' @export
sharpe <- function(rets) {
    .Call(`_FM_sharpe`, rets)
}

#' auto pcor
#'
#' @param dt List
#' @param lags lags
#' @return list
#' @export
autopcor <- function(dt, lags, threads = 1L) {
    .Call(`_FM_autopcor`, dt, lags, threads)
}

#' pcor
#'
#' @param x List
#' @param y numeric vector
#' @param x_sign filter x
#' @param y_sign filter y
#' @return list
#' @export
pcor <- function(x, y = NULL, x_sign = 0L, y_sign = 0L, threads = 1L) {
    .Call(`_FM_pcor`, x, y, x_sign, y_sign, threads)
}

#' rcor
#'
#' @param x List
#' @param y numeric vector
#' @param x_sign filter x
#' @param y_sign filter y
#' @return list
#' @export
rcor <- function(x, y = NULL, x_sign = 0L, y_sign = 0L, threads = 1L) {
    .Call(`_FM_rcor`, x, y, x_sign, y_sign, threads)
}

#' fast_quantile_kernel
#'
#' @param x double vector
#' @param group int vector
#' @param qs double vector contains quantiles
#' @param threads default = 1
#' @export
fast_quantile_kernel <- function(x, group, qs, threads = 1L) {
    .Call(`_FM_fast_quantile_kernel`, x, group, qs, threads)
}

#' dt_quantile
#'
#' @param x List
#' @param q quantile
#' @param threads = 1
#' @return list
#' @export
dt_quantile <- function(x, q, threads = 1L) {
    .Call(`_FM_dt_quantile`, x, q, threads)
}

#' general brownian motion
#'
#' @param ukey ukey
#' @param start_price start_price
#' @param n length
#' @param DataDate date
#' @return list
#' @export
GBM_ohlc <- function(ukey = 1L, start_price = 100, n = 1000L, DataDate = 1L) {
    .Call(`_FM_GBM_ohlc`, ukey, start_price, n, DataDate)
}

#' fm_nan_ratio
#'
#' @param x vector
#' @export
fm_nan_ratio <- function(x) {
    .Call(`_FM_fm_nan_ratio`, x)
}

#' fm_inf_ratio
#'
#' @param x vector
#' @return inf_ratio exclude nan
#' @export
fm_inf_ratio <- function(x) {
    .Call(`_FM_fm_inf_ratio`, x)
}

#' fm_zero_ratio
#'
#' @param x vector
#' @param precision precision
#' @return zero_ratio
#' @export
fm_zero_ratio <- function(x, precision = 1e-9) {
    .Call(`_FM_fm_zero_ratio`, x, precision)
}

#' fm_skew
#'
#' @param x vector
#' @return skew
#' @export
fm_skew <- function(x) {
    .Call(`_FM_fm_skew`, x)
}

#' fm_kurt
#'
#' @param x vector
#' @return kurt
#' @export
fm_kurt <- function(x) {
    .Call(`_FM_fm_kurt`, x)
}

#' fcap
#'
#' @param x List
#' @param lower lower
#' @param upper upper
#' @export
fcap <- function(x, lower = -1., upper = 1.) {
    .Call(`_FM_fcap`, x, lower, upper)
}

#' log_trim
#'
#' @param x vector
#' @export
log_trim <- function(x) {
    .Call(`_FM_log_trim`, x)
}

#' cube root
#'
#' @param x vector
#' @export
cb_rt <- function(x) {
    .Call(`_FM_cb_rt`, x)
}

#' sign_pow
#'
#' @param x vector
#' @export
sign_pow <- function(x, exp) {
    .Call(`_FM_sign_pow`, x, exp)
}

#' all_equal
#'
#' @param x vector
#' @export
fm_all_equal <- function(x, tol = 1e-8, na_rm = FALSE) {
    .Call(`_FM_fm_all_equal`, x, tol, na_rm)
}

#' scale vector based on given mean/sd
#'
#' @param x vector
#' @param mean target mean
#' @param sd target sd
#' @export
vec_scale <- function(x, mean, sd) {
    .Call(`_FM_vec_scale`, x, mean, sd)
}

#' scale vector based on given y's mean/sd
#'
#' @param x vector
#' @param mean target mean
#' @param sd target sd
#' @export
vec_scale_xy <- function(x, y) {
    .Call(`_FM_vec_scale_xy`, x, y)
}

