# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' fm_get_ret
#'
#' @param x vector
#' @param lag lag
#' @param skip skip
#' @export
fm_get_ret <- function(x, lag, skip = 0L) {
    .Call(`_FM_fm_get_ret`, x, lag, skip)
}

#' general brownian motion
#'
#' @param ukey ukey
#' @param start_price start_price
#' @param n length
#' @param DataDate date
#' @return list
#' @export
GBM_ohlc <- function(ukey = 1L, start_price = 100, n = 1000L, DataDate = 1L) {
    .Call(`_FM_GBM_ohlc`, ukey, start_price, n, DataDate)
}

#' fm_nan_ratio
#'
#' @param x vector
#' @export
fm_nan_ratio <- function(x) {
    .Call(`_FM_fm_nan_ratio`, x)
}

#' fm_inf_ratio
#'
#' @param x vector
#' @return inf_ratio exclude nan
#' @export
fm_inf_ratio <- function(x) {
    .Call(`_FM_fm_inf_ratio`, x)
}

#' fm_zero_ratio
#'
#' @param x vector
#' @param precision precision
#' @return zero_ratio
#' @export
fm_zero_ratio <- function(x, precision = 1e-9) {
    .Call(`_FM_fm_zero_ratio`, x, precision)
}

#' fm_skew
#'
#' @param x vector
#' @return skew
#' @export
fm_skew <- function(x) {
    .Call(`_FM_fm_skew`, x)
}

#' fm_kurt
#'
#' @param x vector
#' @return kurt
#' @export
fm_kurt <- function(x) {
    .Call(`_FM_fm_kurt`, x)
}

#' auto pcor
#'
#' @param dt List
#' @param lags lags
#' @return list
#' @export
autopcor <- function(dt, lags) {
    .Call(`_FM_autopcor`, dt, lags)
}

#' pcor
#'
#' @param x List
#' @param y numeric vector
#' @param x_sign filter x
#' @param y_sign filter y
#' @return list
#' @export
pcor <- function(x, y = NULL, x_sign = 0L, y_sign = 0L) {
    .Call(`_FM_pcor`, x, y, x_sign, y_sign)
}

#' rcor
#'
#' @param x List
#' @param y numeric vector
#' @param x_sign filter x
#' @param y_sign filter y
#' @return list
#' @export
rcor <- function(x, y = NULL, x_sign = 0L, y_sign = 0L) {
    .Call(`_FM_rcor`, x, y, x_sign, y_sign)
}

