# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' general brownian motion
#'
#' @param ukey ukey
#' @param start_price start_price
#' @param n length
#' @param DataDate date
#' @return list
#' @export
GBM_ohlc <- function(ukey = 1L, start_price = 100, n = 1000L, DataDate = 1L) {
    .Call(`_FM_GBM_ohlc`, ukey, start_price, n, DataDate)
}

#' fm_nan_ratio
#'
#' @param x vector
#' @export
fm_nan_ratio <- function(x) {
    .Call(`_FM_fm_nan_ratio`, x)
}

#' fm_inf_ratio
#'
#' @param x vector
#' @return inf_ratio exclude nan
#' @export
fm_inf_ratio <- function(x) {
    .Call(`_FM_fm_inf_ratio`, x)
}

#' fm_zero_ratio
#'
#' @param x vector
#' @param precision precision
#' @return zero_ratio
#' @export
fm_zero_ratio <- function(x, precision = 1e-9) {
    .Call(`_FM_fm_zero_ratio`, x, precision)
}

#' fm_skew
#'
#' @param x vector
#' @return skew
#' @export
fm_skew <- function(x) {
    .Call(`_FM_fm_skew`, x)
}

#' fm_kurt
#'
#' @param x vector
#' @return kurt
#' @export
fm_kurt <- function(x) {
    .Call(`_FM_fm_kurt`, x)
}

#' auto pcor
#'
#' @param dt List
#' @param lags lags
#' @return list
#' @export
autopcor <- function(dt, lags) {
    .Call(`_FM_autopcor`, dt, lags)
}

