# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' pvalue_feature_select
#'
#' @param pvalues pvalues
#' @param threshold threshold
#' @param has_intercept has_intercept
#' @return selected feature idx
#' @export
pvalue_feature_select <- function(pvalues, threshold, has_intercept) {
    .Call(`_FT_pvalue_feature_select`, pvalues, threshold, has_intercept)
}

