library(FZ)

(FZ::fz_split("i j k", " "))
(FZ::fz_basename("/tmp/a.txt"))
(FZ::fz_dirname("/tmp/a.txt"))
(FZ::fz_get_absolute_path("~/a.txt"))
(FZ::fz_HumanReadableMillisecond("60ms"))
(FZ::fz_mkdirp("/tmp/a/b/c"))
(FZ::fz_is_dir("/tmp/a/b/c"))
(FZ::fz_is_file_existed("/tmp/a/b/c"))
(FZ::fz_now_cob())
(FZ::fz_now_string())
(FZ::fz_path_wildcard("/tmp/*.pch"))
(FZ::fz_read_trading_days("/dat/ctp/trading_day.txt"))
(FZ::fz_replace_time_placeholder("/dat/ctp/${YYYYMMDD}.txt", 0L))
(FZ::fz_split_instrument_id("IC2309.CFFEX"))

(line <- FZ::str_expand("f%d,tspcor({x1},{x2},{n1})", x1 = "ret", x2 = "ret2", n1 = 3L, expand = F))
(lines <- FZ::str_expand("f%d,tspcor({x1},{x2},{n1})", x1 = "ret", x2 = c("ret2", "ret3"), n1 = 1L:3L, expand = T))
(lines <- sprintf(lines, seq_along(lines)))

(line <- FZ::str_expand2("f1_{N},tspcor({x1},{x2},{n1})", c("x1", "x2"), list(c("ret"), c("ret2"))))
(lines <- FZ::str_expand2("f1_{N},tspcor({x1},{x2},{n1})", c("x1", "x2", "n1"), list(c("ret"), c("ret2", "ret3"), as.character(1L:3L))))
(files <- FZ::expr_split(lines, 5L, "/tmp/a.xml"))
(codes <- FZ::get_cn_fut_code(c(20020000L, 2101L)))
(codes <- FZ::dt_cn_fut_code())
