# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' as_int_group, if nan/inf, then group return -1
#'
#' @param group vector of double
#' @export
as_int_group <- function(group) {
    .Call(`_FF_as_int_group`, group)
}

#' quantile_cut, if nan/inf, factor value will be mapped to 0
#'
#' @param data vector of double
#' @param numQtls number of quantiles
#' @export
qcut <- function(data, numQtls) {
    .Call(`_FF_qcut`, data, numQtls)
}

#' fill_zero, if nan/inf, then return 0
#'
#' @param v vector of double
#' @export
fill_zero <- function(v) {
    .Call(`_FF_fill_zero`, v)
}

#' to_weights
#'
#' @param v vector of double
#' @param demean if vector demean
#' @param equal_weight if vector equal_weight
#' @export
to_weights <- function(v, demean, equal_weight) {
    .Call(`_FF_to_weights`, v, demean, equal_weight)
}

