# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' as_int_group, if nan/inf, then group return -1
#'
#' @param group vector of double
#' @export
as_int_group <- function(group) {
    .Call(`_FF_as_int_group`, group)
}

#' quantile_cut, if nan/inf, factor value will be mapped to 0
#'
#' @param data vector of double
#' @param numQtls number of quantiles
#' @export
qcut <- function(data, numQtls) {
    .Call(`_FF_qcut`, data, numQtls)
}

#' fill_zero, if nan/inf, then return 0
#'
#' @param v vector of double
#' @export
fill_zero <- function(v) {
    .Call(`_FF_fill_zero`, v)
}

#' to_weights
#'
#' @param v vector of double
#' @param demean if vector demean
#' @param equal_weight if vector equal_weight
#' @export
to_weights <- function(v, demean, equal_weight) {
    .Call(`_FF_to_weights`, v, demean, equal_weight)
}

#' as_int_group, if nan/inf, then group return -1
#'
#' @param group vector of int
#' @param name "d" for day, "m" for month, "y" for year
#' @export
time_group <- function(date, name) {
    .Call(`_FF_time_group`, date, name)
}

#' calc_qtl_turnover
#' analyzing the turnover properties of a factor
#'
#' @param dt data table like struct
#' @param qtl_name default "f_qtl"
#' @param shift period default 1
#' @export
calc_qtl_turnover <- function(dt, qtl_name, shift) {
    .Call(`_FF_calc_qtl_turnover`, dt, qtl_name, shift)
}

#' calc_rank_acf
#' Computes autocorrelation of factor ranks
#'
#' @param dt data table like struct
#' @param f_name default "factor"
#' @param shift period default 1
#' @export
calc_rank_acf <- function(dt, f_name, shift) {
    .Call(`_FF_calc_rank_acf`, dt, f_name, shift)
}

