# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' split string
#'
#' @param str string to split
#' @param separator string used to separate
#' @return vector of string
#' @export
fz_split <- function(str, separator) {
    .Call('_FZ_fz_split', PACKAGE = 'FZ', str, separator)
}

