# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' get_cn_fut_code
#'
#' @rdname fz-functions
#' @param ukeys ukey to look up
#' @export
get_cn_fut_code <- function(ukeys, file) {
    .Call(`_FZ_get_cn_fut_code`, ukeys, file)
}

#' all_cn_fut_code
#'
#' @rdname fz-functions
#' @param ukeys ukey to look up
#' @export
all_cn_fut_code <- function(file) {
    .Call(`_FZ_all_cn_fut_code`, file)
}

#' GetUkey
#'
#' @rdname fz-functions
#' @param str ukey string
#' @return ukey int
#' @export
GetUkey <- function(str) {
    .Call(`_FZ_GetUkey`, str)
}

#' GetUkey
#'
#' @rdname fz-functions
#' @param str ukey string
#' @param exch string
#' @return ukey int
#' @export
GetUkey2 <- function(str, exch) {
    .Call(`_FZ_GetUkey2`, str, exch)
}

#' split string
#'
#' @rdname fz-functions
#' @param str string to split
#' @param separator string used to separate
#' @return vector of string
#' @export
fz_split <- function(str, separator) {
    .Call(`_FZ_fz_split`, str, separator)
}

#' SplitInstrumentID
#'
#' @rdname fz-functions
#' @param str string to split
#' @return std::vector of string
#' @export
fz_split_instrument_id <- function(str) {
    .Call(`_FZ_fz_split_instrument_id`, str)
}

#' now_string
#'
#' @rdname fz-functions
#' @return string
#' @export
fz_now_string <- function() {
    .Call(`_FZ_fz_now_string`)
}

#' now_cob
#'
#' @rdname fz-functions
#' @return int64_t
#' @export
fz_now_cob <- function() {
    .Call(`_FZ_fz_now_cob`)
}

#' HumanReadableMillisecond like 20us
#'
#' @rdname fz-functions
#' @param interval_string what to work
#' @return uint64_t
#' @export
fz_HumanReadableMillisecond <- function(interval_string) {
    .Call(`_FZ_fz_HumanReadableMillisecond`, interval_string)
}

#' replace_time_placeholder
#'
#' @rdname fz-functions
#' @param str what to work
#' @param date which date to use
#' @return string
#' @export
fz_replace_time_placeholder <- function(str, date) {
    .Call(`_FZ_fz_replace_time_placeholder`, str, date)
}

#' mkdirp
#'
#' @rdname fz-functions
#' @param path where to work
#' @return bool success
#' @export
fz_mkdirp <- function(path) {
    .Call(`_FZ_fz_mkdirp`, path)
}

#' IsFileExisted
#'
#' @rdname fz-functions
#' @param path where to work
#' @return bool success
#' @export
fz_is_file_existed <- function(path) {
    .Call(`_FZ_fz_is_file_existed`, path)
}

#' GetAbsolutePath
#'
#' @rdname fz-functions
#' @param path where to work
#' @return string
#' @export
fz_get_absolute_path <- function(path) {
    .Call(`_FZ_fz_get_absolute_path`, path)
}

#' Dirname
#'
#' @rdname fz-functions
#' @param path where to work
#' @return string
#' @export
fz_dirname <- function(path) {
    .Call(`_FZ_fz_dirname`, path)
}

#' Basename
#'
#' @rdname fz-functions
#' @param path where to work
#' @return string
#' @export
fz_basename <- function(path) {
    .Call(`_FZ_fz_basename`, path)
}

#' IsDir
#'
#' @rdname fz-functions
#' @param path where to test
#' @return bool success
#' @export
fz_is_dir <- function(path) {
    .Call(`_FZ_fz_is_dir`, path)
}

#' read_trading_days
#'
#' @rdname fz-functions
#' @param path where to read
#' @param start start date
#' @param end end date
#' @return vector of dates
#' @export
fz_read_trading_days <- function(path, start = -1L, end = -1L) {
    .Call(`_FZ_fz_read_trading_days`, path, start, end)
}

#' path wildcard like /tmp/*.csv
#'
#' @rdname fz-functions
#' @param path where to search
#' @return map <matched, path>
#' @export
fz_path_wildcard <- function(path) {
    .Call(`_FZ_fz_path_wildcard`, path)
}

#' str_expand2
#'
#' @rdname fz-functions
#' @param expr expr to expand
#' @param names names to expand
#' @param values values to expand
#' @return vector of strs
#' @export
str_expand2 <- function(expr, names, values) {
    .Call(`_FZ_str_expand2`, expr, names, values)
}

#' expr_split
#'
#' @rdname fz-functions
#' @param exprs expr to split
#' @param N N to split
#' @param config_path meta config file
#' @export
expr_split <- function(exprs, N, config_path) {
    .Call(`_FZ_expr_split`, exprs, N, config_path)
}

#' expr_split_to_dt
#'
#' @rdname fz-functions
#' @param exprs expr to split
#' @param delimiter delimiter to split
#' @param is_first true first, false last
#' @export
expr_split_to_dt <- function(exprs, delimiter, is_first = TRUE) {
    .Call(`_FZ_expr_split_to_dt`, exprs, delimiter, is_first)
}

